### ISSUE TITLE
Missing images and code

### ISSUE THREAD

**Issue by celery-ship-it** [google/haloquest#1]
I thank the authors for their great work! However, some of the images in the dataset are unavailable now. For example, ['5616_15602534299_2c05a69cdf_o.jpg'](https://farm2.staticflickr.com/5616/15602534299_2c05a69cdf_o.jpg) and ['9_8451_8032464156_50e0b58cd9_o.jpg'](https://c8.staticflickr.com/9/8451/8032464156_50e0b58cd9_o.jpg) are missing in the eval split, and much more in the train split. Can you share the missing images? Also, the [link](https://github.com/ZhecanJamesWang/Hallucinated-Visual-Question-Answering) to the code to reproduce the experiments is not working.

**Comment by ZhecanJamesWang** [comment]
I believe all the missing images are real images from Open Images. We are working on fixing those unavailable images. The link should be working now.

**Comment by celery-ship-it** [comment]
Thank you for the response and the link. I hope the missing images are available soon.
